# Generated by Django 4.2.9 on 2024-01-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='events',
        ),
    ]
